Repository armosec/armoapi-go, pull requests merged in 2023-08, with the labels that each got.

#118 Postgres Models Implementation
  postgresmodels/pagination.go
  postgresmodels/posture.go
Labels: enhancement

#137 alert channels update
  broadcastevents/events_test.go
  broadcastevents/factory.go
  broadcastevents/fixtures/alertChannel.json
Labels: enhancement, Tests

#138 Fix vul primary key
  armotypes/posturetypes.go
  postgresmodels/attackchains.go
Labels: Refactoring

#139 fix AC Vulnerabilities
  armotypes/attackchainstypes.go
Labels: Refactoring

#140 minor fix
  armotypes/attackchainstypes.go
Labels: Refactoring

#141 remove old postgres baseReport
  postgresmodels/containerscan.go
  postgresmodels/pagination.go
Labels: Refactoring
