Repository armosec/armoapi-go, pull requests merged in 2023-12, with the labels that each got.

#179 feat: add networkpolicies types
  armotypes/networkpolicies.go
Labels: enhancement

#178 sub-2516 - Slack notification models
  armotypes/customerslackconfigurations.go
  armotypes/oauth2types.go
Labels: Refactoring

#180 sub-2516 - Slack notification models
  notifications/collaborationconfig.go
Labels: enhancement

#181 Sub 2516 status obj
  armotypes/portaltypes.go
  notifications/usersnotificationsmethods.go
Labels: enhancement

#182 SUB-3580 | change remove provider config logic to set empty slice
  notifications/usernotificationreporttypes_test.go
  notifications/usersnotificationsmethods.go
Labels: enhancement, Tests

#183 add labels to kubernetes object
  armotypes/kubernetes_objects.go
Labels: enhancement

#184 added resourceHash
  armotypes/kubernetes_objects.go
Labels: enhancement

#185 fix: change name of np attribute
  armotypes/networkpolicies.go
Labels: bug_fix

#186 Update events.go
  broadcastevents/events.go
Labels: enhancement

#187 SUB-3621 - Slack alerts - Wrong CVE link for GHSA vuln
  containerscan/commonadapters.go
  containerscan/commonadapters_test.go
Labels: Tests, bug_fix

#189 add cluster short name
  identifiers/designators.go
Labels: enhancement

#188 add kev vulnerability fields
  armotypes/vulnerabilitytypes.go
Labels: enhancement

#191 network policie status
  armotypes/kubernetes_objects.go
Labels: enhancement

#190 Sub 3621 vulnerabilities + workloads structs + enrichments
  armotypes/common.go
  armotypes/vulnerabilitytypes.go
Labels: enhancement

#192 SUB-3589 - Risk factors
  armotypes/common.go
  armotypes/common_test.go
Labels: enhancement, Tests

#194 revert
  armotypes/vulnerabilitytypes.go
Labels: enhancement
