Repository armosec/armoapi-go, pull requests merged in 2023-09, with the labels that each got.

#142 minor
  postgresmodels/containerscan.go
Labels: Refactoring

#143 Migrations from dash be and to pg connector
  containerscan/commondatastructures.go
  containerscan/consts.go
  containerscan/overtime_structs.go
  go.mod
  go.sum
  notifications/gojay.go
  postgresmodels/attackchains.go
  postgresmodels/containerscan.go
  postgresmodels/pagination.go
  postgresmodels/posture.go
  postgresmodels/types.go
Labels: enhancement, Refactoring

#145 add func getControlIDsFromAllNodes
  armotypes/attackchainstypesutils.go
  armotypes/attackchainstypesutils_test.go
Labels: enhancement, Tests

#146 stable "multiple providers with single channel each" test
  notifications/usernotificationreporttypes_test.go
Labels: Tests

#147 export func
  armotypes/attackchainstypesutils.go
  armotypes/attackchainstypesutils_test.go
Labels: Refactoring

#150 fix event time in posture events
  broadcastevents/events_test.go
  broadcastevents/factory.go
Labels: Refactoring

#148 move pulsar stuff
  armotypes/attackchainstypes.go
Labels: Refactoring

#151 add attackChainsLastScan to customer state
  armotypes/portaltypes.go
Labels: enhancement

#144 SUB-2413 | add cluster short name to the scope
  notifications/alertchannelapi.go
  notifications/alertchannelapi_test.go
  notifications/alertchannelapimethods.go
  notifications/usernotificationreporttypes.go
Labels: enhancement

#152 add generic request struct
  armotypes/pagination_structs.go
Labels: Refactoring

#153 add container to attack chain
  armotypes/attackchainstypes.go
  identifiers/designators.go
Labels: enhancement

#154 added processing status. added AttackChainNode Equals
  armotypes/attackchainstypes.go
Labels: enhancement

#156 Migrate from dash be
  apis/websocketmethodutils.go
  armotypes/microservice_info.go
  armotypes/microservice_info_method.go
  go.mod
  go.sum
Labels: Refactoring

#157 comparing ac node description and name
  armotypes/attackchainstypes.go
Labels: enhancement

#155 add attackChainState to portal cluster
  armotypes/portaltypes.go
Labels: enhancement

#159 add ProcessingStatusTimeout
  armotypes/attackchainstypes.go
Labels: enhancement

#160 rm apiversion from resource hash
  identifiers/designators.go
Labels: Refactoring

#161 add S3ObjectPath
  identifiers/raw_resource_loc.go
Labels: enhancement
