Repository armosec/armoapi-go, pull requests merged in 2024-07, with the labels that each got.

#346 Removing ptr from interface type
  armotypes/runtimeincidents.go
  armotypes/runtimeincidents_test.go
Labels: Bug fix, Review effort [1-5]: 1

#345 add AppliedNetworkPolicyType to SecurityIssueControl
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 2

#347 Sr vuln type
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 2

#348 feat: remove incidents
  armotypes/runtimeincidents.go
Labels: enhancement, Review effort [1-5]: 2

#349 added risk factors to workload statuses
  armotypes/workloadstatus.go
Labels: enhancement, Review effort [1-5]: 2

#350 feat: Add attributes for nodeName and podName in identifiers
  identifiers/designators.go
  notifications/runtimeincidents.go
  notifications/usernotificationreporttypes.go
Labels: enhancement, Review effort [1-5]: 2, other
