Repository armosec/armoapi-go, pull requests merged in 2024-02, with the labels that each got.

#223 add new getting started fields
  armotypes/portaltypes.go
Labels: enhancement, Review effort [1-5]: 1

#224 revert omitempty
  armotypes/postureexceptionpolicytypes.go
  armotypes/vulnerabilityexceptionpolicytypes.go
Labels: Bug fix, Review effort [1-5]: 1

#225 Adding SBOM attribute
  identifiers/designators.go
Labels: enhancement, Review effort [1-5]: 1

#226 Add security risk types and structures
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 2

#227 CountFields option for unique-values request
  armotypes/pagination_structs.go
  armotypes/pagination_structs_methods.go
Labels: enhancement, Review effort [1-5]: 2

#228 Fix json tag
  armotypes/pagination_structs.go
Labels: bug_fix, Review effort [1-5]: 1

#231 Scan types
  armotypes/common.go
Labels: enhancement, Review effort [1-5]: 2

#232 support unique values pagination
  armotypes/pagination_structs_methods.go
Labels: enhancement, Review effort [1-5]: 2

#233 Add vulnerabilitiesKinds count to cords
  containerscan/overtime_structs.go
Labels: enhancement, Review effort [1-5]: 2

#234 uin =? int64
  containerscan/overtime_structs.go
Labels: enhancement, Review effort [1-5]: 1

#235 Refactor SecurityRisk struct and add new interface ISecurityIssue
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 3

#236 Add SecurityRiskName field to SecurityIssuesSummary struct
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 1

#237 SUB-3576 - Ignore rule - the user cannot edit from "dates" to "never"…
  armotypes/postureexceptionpolicytypes.go
  armotypes/vulnerabilityexceptionpolicytypes.go
Labels: bug_fix, Review effort [1-5]: 2

#238 Update SecurityIssues structs
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 2

#239 Add new fields for detected and resolved resources count
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 1

#240 Update dependencias
  .github/workflows/pr.yaml
  .github/workflows/release.yaml
  go.mod
  go.sum
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#242 Add SecurityIssueResource struct and update SecurityIssuesSummary struct
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 2

#243 Add 'Kind' field to SecurityIssueResource struct
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 1

#241 synchronizer client model
  armotypes/synchronizerclients.go
Labels: enhancement, Review effort [1-5]: 2
