Repository armosec/armoapi-go, pull requests merged in 2024-01, with the labels that each got.

#195 Add arrayMatch operator
  armotypes/pagination_structs.go
Labels: enhancement

#196 np fixes
  armotypes/kubernetes_objects.go
  armotypes/networkpolicies.go
Labels: bug_fix

#197 sub-3604 - Add workload id
  armotypes/vulnerabilitytypes.go
Labels: enhancement

#199 add score fields
  armotypes/vulnerabilitytypes.go
Labels: enhancement

#200 change cvss score fields types
  armotypes/vulnerabilitytypes.go
Labels: enhancement

#202 update network policy status structs
  armotypes/kubernetes_objects.go
  armotypes/networkpolicies.go
Labels: enhancement

#201 Enrich vuln report
  containerscan/commonContainerScanSummaryResultMethods.go
  containerscan/commondatastructures.go
  containerscan/containerscan_mock.go
  containerscan/containerscan_test.go
  containerscan/gojayunmarshaller.go
  containerscan/interfaces.go
  containerscan/rawdatastrucutres.go
  containerscan/vulnerabilityMethods.go
Labels: enhancement

#204 Fix cluster name field
  armotypes/vulnerabilitytypes.go
Labels: bug_fix

#205 update vulnerability type
  armotypes/vulnerabilitytypes.go
Labels: enhancement

#206 calc resource hash
  identifiers/utils.go
Labels: enhancement

#207 Image summary
  armotypes/vulnerabilitytypes.go
Labels: enhancement

#208 add kev possible values
  armotypes/vulnerabilitytypes.go
Labels: enhancement

#209 add wlid to vulnerability
  armotypes/vulnerabilitytypes.go
Labels: enhancement

#210 Missing interface method
  containerscan/interfaces.go
Labels: enhancement

#213 fix fields typos
  armotypes/vulnerabilitytypes.go
Labels: Bug fix

#212 component paths
  armotypes/vulnerabilitytypes.go
Labels: enhancement

#214 add IgnoreRuleSummary type
  armotypes/vulnerabilitytypes.go
Labels: enhancement

#216 add cvss v2 fields
  armotypes/vulnerabilitytypes.go
Labels: enhancement

#217 CVE First-Seen in the account
  armotypes/vulnerabilitytypes.go
Labels: enhancement

#218 bump docker/docker version
  apis/interfaces.go
  apis/websocketdatastructures.go
  apis/websocketmethods.go
  apis/websocketmethods_test.go
  go.mod
  go.sum
Labels: enhancement

#219 SUB-3576 - Ignore rule - the user cannot edit from "dates" to "never"…
  armotypes/postureexceptionpolicytypes.go
  armotypes/vulnerabilityexceptionpolicytypes.go
Labels: Bug fix

#220 support for payment ph2
  armotypes/portaltypes.go
Labels: enhancement, Review effort [1-5]: 1

#221 Avoid validating page properties more than once
  armotypes/datastructuresmethod_test.go
  armotypes/pagination_structs.go
  armotypes/pagination_structs_methods.go
Labels: enhancement, Review effort [1-5]: 2

#222 SUB-4015 - change risk factors internet facing
  armotypes/common.go
  armotypes/common_test.go
Labels: enhancement, Review effort [1-5]: 1
