Repository armosec/armoapi-go, pull requests merged in 2024-03, with the labels that each got.

#246 Add ExceptionApplied field to SecurityIssue struct
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 1

#247 Refactor exception policy and identifiers***
  armotypes/exceptionpolicy.go
  identifiers/designators.go
  identifiers/designators_methods.go
  identifiers/designators_methods_test.go
  identifiers/utils.go
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#245 SUB-3743 - Component view - show the latest fix version
  go.mod
  go.sum
  packages_versions/apk_version.go
  packages_versions/deb_version.go
  packages_versions/gemfile_version.go
  packages_versions/golang_version.go
  packages_versions/golang_version_test.go
  packages_versions/kb_version.go
  packages_versions/maven_version.go
  packages_versions/maven_version_test.go
  packages_versions/pep440_version.go
  packages_versions/portage_version.go
  packages_versions/rpm_version.go
  packages_versions/rpm_version_test.go
  packages_versions/semantic_version.go
  packages_versions/version.go
  packages_versions/version_test.go
Labels: enhancement, other, Review effort [1-5]: 4

#250 Sub 3743
  packages_versions/version.go
  packages_versions/version_test.go
Labels: enhancement, Tests, Review effort [1-5]: 2

#251 Update SecurityIssue struct in securityrisks.go
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 2

#249 SUB-2558 | add container paths to image summary
  armotypes/vulnerabilitytypes.go
Labels: enhancement, Review effort [1-5]: 1

#253 remove package_versions
  go.mod
  go.sum
  packages_versions/apk_version.go
  packages_versions/deb_version.go
  packages_versions/gemfile_version.go
  packages_versions/golang_version.go
  packages_versions/golang_version_test.go
  packages_versions/kb_version.go
  packages_versions/maven_version.go
  packages_versions/maven_version_test.go
  packages_versions/pep440_version.go
  packages_versions/portage_version.go
  packages_versions/rpm_version.go
  packages_versions/rpm_version_test.go
  packages_versions/semantic_version.go
  packages_versions/version.go
  packages_versions/version_test.go
Labels: enhancement, Review effort [1-5]: 2

#254 restore package_versions
  go.mod
  go.sum
  package_versions/apk_version.go
  package_versions/deb_version.go
  package_versions/gemfile_version.go
  package_versions/golang_version.go
  package_versions/golang_version_test.go
  package_versions/kb_version.go
  package_versions/maven_version.go
  package_versions/maven_version_test.go
  package_versions/pep440_version.go
  package_versions/portage_version.go
  package_versions/rpm_version.go
  package_versions/rpm_version_test.go
  package_versions/semantic_version.go
  package_versions/version.go
  package_versions/version_test.go
Labels: enhancement, other, Review effort [1-5]: 4

#255 Add methods to get and set cluster names in SecurityIssue struct
  armotypes/securityrisks.go
Labels: enhancement

#256 Fix sr interfaces
  armotypes/securityrisks.go
Labels: enhancement

#257 Refactor SecurityIssue methods to use pointer receiver
  armotypes/securityrisks.go
  armotypes/securityrisks_test.go
Labels: enhancement, Tests, Review effort [1-5]: 2

#258 Add fields for enrichment of RelatedResources
  armotypes/attackchainstypes.go
Labels: enhancement, Review effort [1-5]: 2

#259 minor fix - allow field to be omitempty
  armotypes/attackchainstypes.go
Labels: enhancement, Review effort [1-5]: 1

#260 SUB-2558 | add array for each column
  armotypes/vulnerabilitytypes.go
Labels: enhancement, Review effort [1-5]: 2

#261 SUB-2558 | remove workload hash
  armotypes/vulnerabilitytypes.go
Labels: enhancement, Review effort [1-5]: 1

#262 Add ResourcesDeletedLastChange field to SecurityIssuesSummary struct
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 2

#264 add FixByNetworkPolicy indicator
  armotypes/posturetypes.go
Labels: enhancement, Review effort [1-5]: 1

#263 Pod Statuses
  armotypes/podstatus.go
Labels: enhancement, Review effort [1-5]: 2

#265 Add SecurityIssuePushNotification and NotificationTypeSecurityRiskNew
  notifications/securityrisks.go
  notifications/usernotificationreporttypes.go
Labels: enhancement, Review effort [1-5]: 2

#268 Refactor notification-related test and method
  notifications/usernotificationreporttypes_test.go
  notifications/usersnotificationsmethods.go
Labels: enhancement, Tests, Review effort [1-5]: 2

#267 Missing runtime info reason
  armotypes/networkpolicies.go
Labels: enhancement, Review effort [1-5]: 2

#269 Add smart remediation support to posture types
  armotypes/posturetypes.go
Labels: enhancement, Review effort [1-5]: 2

#270 Update SecurityRisk struct with SmartRemediation field
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 2

#271 Add RuntimeIncident
  armotypes/runtimeincidents.go
Labels: enhancement, Review effort [1-5]: 3

#272 Update deprecated smart remediation field
  armotypes/posturetypes.go
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 2

#273 Add Name field to ControlInfo struct
  armotypes/posturetypes.go
Labels: enhancement, Review effort [1-5]: 1

#274 SUB-4455 | add images field to workload summary
  armotypes/vulnerabilitytypes.go
Labels: enhancement, Review effort [1-5]: 1
