Repository armosec/armoapi-go, pull requests merged in 2024-05, with the labels that each got.

#305 Update bson tags in RuntimeAlert struct
  armotypes/runtimeincidents.go
Labels: enhancement

#308 Sr tickets
  armotypes/securityrisks.go
  identifiers/designators.go
  notifications/integrationref.go
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#309 Refactor EntityIdentifiers.Validate() method to handle EntityTypeSecu…
  notifications/integrationref.go
Labels: enhancement, Review effort [1-5]: 2

#311 Adapt incidents to KDR google sheet
  armotypes/runtimeincidents.go
Labels: enhancement, Review effort [1-5]: 2

#312 Refactor RuntimeIncident struct fields in runtimeincidents.go
  armotypes/runtimeincidents.go
Labels: enhancement, Review effort [1-5]: 2

#316 Add runtime incident resolved status fields
  armotypes/runtimeincidents.go
Labels: enhancement, Review effort [1-5]: 2

#318 update node profiles structures
  armotypes/crds_test.go
  armotypes/nodesProfile.go
  armotypes/nodesProfile_test.go
Labels: enhancement, Review effort [1-5]: 2

#319 ```text
  armotypes/runtimeincidents.go
Labels: enhancement, Review effort [1-5]: 1

#320 add unique findings types
  armotypes/vulnerabilitytypes.go
Labels: enhancement, Review effort [1-5]: 2

#322 use bool ptr for FixAvailable
  armotypes/vulnerabilitytypes.go
Labels: enhancement

#323 chore: Add CurrentState field to NodeProfile and PodContainer
  armotypes/nodesProfile.go
  armotypes/podstatus.go
Labels: enhancement, Review effort [1-5]: 1

#328 Changing the upper layer field to be ptr
  armotypes/runtimeincidents.go
Labels: Bug fix

#327 add paths to component summary type
  armotypes/vulnerabilitytypes.go
Labels: enhancement, Review effort [1-5]: 2
