Repository armosec/armoapi-go, pull requests merged in 2024-11, with the labels that each got.

#386 Adding trace + process fields
  armotypes/runtimeincidents.go
  armotypes/runtimeincidents_test.go
Labels: Review effort [1-5]: 2

#388 Removing provider type
  armotypes/runtimeincidents.go
Labels: Review effort [1-5]: 2

#390 add checkType map
  armotypes/cloudposturetypes.go
Labels: Review effort [1-5]: 2

#392 add nexus provider and add base funcs
  armotypes/registrymethods.go
  armotypes/registrytypes.go
Labels: Review effort [1-5]: 3

#393 * remove idle status * add gar key field
  armotypes/registrymethods.go
  armotypes/registrytypes.go
Labels: Review effort [1-5]: 2

#394 use map[string]interface for gar key
  armotypes/registrymethods.go
Labels: Review effort [1-5]: 2

#395 change registry in progress status to upper case
  armotypes/registrytypes.go
Labels: Review effort [1-5]: 1

#397 add description and packageVersion fields to AggregatedVulnerability …
  notifications/vulnerability.go
Labels: Review effort [1-5]: 2

#399 Added old image field
  armotypes/runtimeincidents.go
Labels: Review effort [1-5]: 1

#400 add registry attributes
  armotypes/registrytypes.go
  identifiers/designators.go
Labels: Review effort [1-5]: 1

#401 * add clean registry url * add project id field to google registry
  armotypes/registrymethods.go
  armotypes/registrytypes.go
Labels: Review effort [1-5]: 3

#402 fix: add missing bson tags for CVSS fields in AggregatedVulnerability…
  notifications/vulnerability.go
Labels: Review effort [1-5]: 1
