Repository armosec/armoapi-go, pull requests merged in 2024-06, with the labels that each got.

#332 add image manifest getters/setters to ContainerScanSummaryResult inte…
  containerscan/commonContainerScanSummaryResultMethods.go
  containerscan/interfaces.go
Labels: enhancement, Review effort [1-5]: 2

#333 feat: Add SeccompWorkload type and constants
  armotypes/seccomp.go
Labels: enhancement, Review effort [1-5]: 2

#334 add WorkloadStatus
  armotypes/workloadstatus.go
Labels: enhancement, Review effort [1-5]: 2

#336 SUB-4975 | add image layer type
  armotypes/vulnerabilitytypes.go
Labels: enhancement, Review effort [1-5]: 2

#337 feat: Update ContainerStatus struct to include multiple architectures
  armotypes/containers.go
Labels: enhancement, Review effort [1-5]: 2

#339 feat: Add K8sResourceHash field to SeccompWorkload
  armotypes/seccomp.go
Labels: enhancement, Review effort [1-5]: 1

#338 Adding admission type
  armotypes/runtimeincidents.go
Labels: enhancement, Review effort [1-5]: 3

#340 add base image type
  armotypes/vulnerabilitytypes.go
Labels: enhancement, Review effort [1-5]: 2

#341 Changing request to attrs
  armotypes/runtimeincidents.go
  go.mod
  go.sum
Labels: enhancement, Review effort [1-5]: 2

#344 Seccomp fix
  armotypes/seccomp.go
Labels: enhancement, Bug fix, Review effort [1-5]: 1

#343 add AppliedNetworkPolicyType to NetworkPoliciesWorkload
  armotypes/networkpolicies.go
Labels: enhancement, Review effort [1-5]: 1
