Repository armosec/armoapi-go, pull requests merged in 2024-09, with the labels that each got.

#361 runtime exception policies
  armotypes/runtimeincidents.go
Labels: enhancement, Review effort [1-5]: 1

#362 feat: Add Jira attributes and workflow parameters
  identifiers/designators.go
  notifications/usernotificationreporttypes.go
Labels: enhancement, Review effort [1-5]: 2

#363 refactor: Update SecurityRiskID field to SecurityRiskIDs slice
  notifications/usernotificationreporttypes.go
Labels: enhancement, Review effort [1-5]: 1

#364 Cspm consts
  armotypes/cloudposturetypes.go
  identifiers/designators.go
Labels: enhancement, Review effort [1-5]: 2

#365 add scan statuses consts
  armotypes/cloudposturetypes.go
  identifiers/designators.go
Labels: enhancement, Review effort [1-5]: 1

#366 add opposite maps to intToValue
  armotypes/cloudposturetypes.go
Labels: enhancement, Review effort [1-5]: 2

#367 add registry types
  armotypes/registrytypes.go
Labels: enhancement, Review effort [1-5]: 2

#368 add nodeStatus event and test
  broadcastevents/events.go
  broadcastevents/events_test.go
  broadcastevents/factory.go
Labels: enhancement, Tests, Review effort [1-5]: 2

#370 Add enableWorkflows field to NotificationsConfig
  notifications/usernotificationreporttypes.go
Labels: enhancement, Review effort [1-5]: 2

#371 change checkStatuses ints and order
  armotypes/cloudposturetypes.go
Labels: enhancement, Review effort [1-5]: 2
