Repository armosec/armoapi-go, pull requests merged in 2024-10, with the labels that each got.

#372 add check statuses consts
  armotypes/cloudposturetypes.go
Labels: Review effort [1-5]: 2

#374 workflows vuln configservice struct values extension
  armotypes/vulnerabilitytypes.go
  go.mod
  go.sum
  notifications/collaborationconfig.go
  notifications/usernotificationreporttypes.go
  notifications/vulnerability.go
Labels: enhancement, Review effort [1-5]: 3, dependencies

#375 synchronizer client new fields
  armotypes/synchronizerclients.go
Labels: enhancement, Review effort [1-5]: 1

#376 Refactor NotificationsConfig struct and remove unused methods
  configservice/customer.go
  notifications/usernotificationreporttypes.go
  notifications/usernotificationreporttypes_test.go
  notifications/usersnotificationsmethods.go
Labels: enhancement, Tests, Review effort [1-5]: 2

#377 registry types
  apis/clusterapis.go
  armotypes/helmconsts.go
  armotypes/k8stypes.go
  armotypes/registrymethods.go
  armotypes/registrytypes.go
Labels: enhancement, Review effort [1-5]: 4

#378 add set base func
  armotypes/registrymethods.go
  armotypes/registrytypes.go
Labels: enhancement, Review effort [1-5]: 2

#379 registry types omitempty secret
  armotypes/registrytypes.go
Labels: enhancement, Review effort [1-5]: 2

#380 Bump dependencies
  go.mod
  go.sum
  package_versions/version.go
Labels: enhancement, Review effort [1-5]: 2, dependencies

#381 add check types
  armotypes/cloudposturetypes.go
Labels: enhancement, Review effort [1-5]: 1

#382 fix checktypes + add both check type
  armotypes/cloudposturetypes.go
Labels: enhancement, Review effort [1-5]: 1

#383 add status attribute
  identifiers/designators.go
Labels: enhancement, Review effort [1-5]: 1

#384 change unknown to 0
  armotypes/cloudposturetypes.go
Labels: Review effort [1-5]: 2

#385 add registry statuses
  armotypes/registrytypes.go
Labels: enhancement, Review effort [1-5]: 2
