Repository armosec/armoapi-go, pull requests merged in 2024-04, with the labels that each got.

#275 add scan status attributes
  identifiers/designators.go
Labels: enhancement, Review effort [1-5]: 2

#276 Add SecurityIssuesTrends and SecurityIssuesTrendsSummary structs
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 2

#277 add resource hash to vuln-wl and posture resource
  armotypes/posturetypes.go
  armotypes/vulnerabilitytypes.go
Labels: enhancement, Review effort [1-5]: 2

#278 K8s resource status
  armotypes/kubernetes_objects.go
Labels: enhancement, Review effort [1-5]: 1

#281 Refactor runtime incident structs and add new alert types
  armotypes/runtimeincidents.go
Labels: enhancement, Review effort [1-5]: 3

#282 SUB-3670 | swagger ignore first seen and supportSmartRemediation fields
  armotypes/posturetypes.go
  armotypes/securityrisks.go
  armotypes/vulnerabilitytypes.go
Labels: enhancement, Review effort [1-5]: 2

#284 Adding new type of rule description
  armotypes/runtimeincidents.go
Labels: enhancement, Review effort [1-5]: 1

#279 Tickets
  armotypes/integrationtypes.go
  armotypes/pagination_structs.go
  armotypes/posturetypes.go
  armotypes/reposcanning.go
  armotypes/runtimeincidents.go
  armotypes/vulnerabilitytypes.go
  identifiers/designators.go
  notifications/integration_test.go
  notifications/integrationref.go
Labels: documentation, enhancement, Review effort [1-5]: 4

#285 Add file path to ref entity
  notifications/integration_test.go
  notifications/integrationref.go
Labels: enhancement, Review effort [1-5]: 2

#287 Refactor SecurityIssuesSummary struct in securityrisks.go
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 2

#288 Add Not equal operator
  armotypes/pagination_structs.go
Labels: enhancement, Review effort [1-5]: 1

#289 Add ResolvedReason type to securityrisks.go
  armotypes/securityrisks.go
Labels: enhancement

#286 Fixing types we don't have for sure
  armotypes/runtimeincidents.go
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#290 Adding new process tree and fixing deprecated fields
  armotypes/runtimeincidents.go
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#291 interface to map
  notifications/integrationref.go
Labels: enhancement

#292 Fix json tag
  armotypes/integrationtypes.go
Labels: bug_fix, Review effort [1-5]: 1

#293 Add "type" to entity map
  notifications/integrationref.go
Labels: enhancement

#294 Add ProcessTree to RuntimeIncident struct
  armotypes/runtimeincidents.go
Labels: enhancement, Review effort [1-5]: 2

#295 Update ExpirationTime field to ExpirationDate in BaseExceptionPolicy
  armotypes/exceptionpolicy.go
Labels: enhancement, Review effort [1-5]: 1

#296 Remove ns validation from tickets resources owners
  notifications/integration_test.go
  notifications/integrationref.go
Labels: enhancement

#297 Fix resource field in BaseExceptionPolicy and add Exception field in SecurityIssue
  armotypes/exceptionpolicy.go
  armotypes/securityrisks.go
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#298 Making some fields pointers and removing ptr from fields
  armotypes/runtimeincidents.go
Labels: enhancement, Review effort [1-5]: 2

#299 Remove unused Exception field in SecurityIssue struct
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 1

#300 don't return error on missing provider
  notifications/usernotificationreporttypes_test.go
  notifications/usersnotificationsmethods.go
Labels: enhancement, Review effort [1-5]: 2

#301 Update SecurityIssuesTrends struct in securityrisks.go
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 2

#302 Fix formatting in SecurityIssue struct
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 2

#303 Update RiskType values in securityrisks.go
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 2

#304 Add MissingRuntimeInfoReason field to SecurityIssueControl struct in …
  armotypes/securityrisks.go
Labels: enhancement, Review effort [1-5]: 1
