Repository armosec/armoapi-go, pull requests merged in 2025-04, with the labels that each got.

#474 network stream struct
  armotypes/networkstream.go
Labels: Review effort 2/5

#421 Add DefaultFrameworks field to InstallationData struct
  armotypes/portaltypes.go
Labels: Review effort [1-5]: 1

#477 add azure config consts
  identifiers/designators.go
Labels: Review effort 1/5

#478 network connection type
  armotypes/networkconnection.go
Labels: Review effort 1/5

#479 add Children migration in findProcssRecursive
  armotypes/runtimeincidents.go
Labels: Review effort 1/5

#480 Adding dns protocol
  armotypes/networkstream.go
Labels: Review effort 1/5

#481 Adding host support
  armotypes/networkstream.go
Labels: Review effort 1/5

#483 Add CreatedBy field to Ticket struct for tracking user creation
  armotypes/integrationtypes.go
Labels: Review effort 1/5

#485 workload name field
  armotypes/vulnerabilitytypes.go
Labels: Review effort 1/5

#486 bump vulnerable go-jose dependencies
  apis/login.go
  go.mod
  go.sum
Labels: Review effort 2/5

#488 Bump github.com/cilium/cilium to v1.16.9
  go.mod
  go.sum
Labels: Review effort 1/5
