Repository armosec/armoapi-go, pull requests merged in 2025-02, with the labels that each got.

#435 Refactor validation error messages for EntityTypeCloudRule
  notifications/integrationref.go
Labels: Review effort [1-5]: 1

#436 Adding anomaly details to struct
  armotypes/runtimeincidents.go
Labels: Review effort [1-5]: 1

#437 Add Provider field to CdrAlertBatch struct
  armotypes/cdr/cdr.go
Labels: Review effort [1-5]: 1

#438 Added malware metadata struct
  armotypes/linuxobjects.go
  armotypes/runtimeincidents.go
Labels: Review effort [1-5]: 3

#439 Setting the anomaly flag on a frame
  armotypes/runtimeincidents.go
Labels: Review effort [1-5]: 2

#440 Added malware signature struct
  armotypes/malware.go
Labels: Review effort [1-5]: 1

#442 add secondRuleHash
  identifiers/designators.go
Labels: Review effort [1-5]: 1

#443 updated malware alert with signature
  armotypes/runtimeincidents.go
Labels: Review effort [1-5]: 2

#444 add new checkStatus
  armotypes/cloudposturetypes.go
Labels: Review effort 1/5

#445 Added omit empty to malware signature
  armotypes/malware.go
Labels: Review effort 1/5

#446 added network scan alert
  armotypes/runtimeincidents.go
Labels: Review effort 1/5

#447 Putting MalwareDescription field back
  armotypes/runtimeincidents.go
Labels: Review effort 1/5

#448 Adding network scan alert type
  armotypes/runtimeincidents.go
Labels: Review effort 1/5

#449 Changing alert to contain addresses
  armotypes/runtimeincidents.go
Labels: Review effort 1/5

#450 deprecate control name in posture exception policies
  armotypes/postureexceptionpolicytypes.go
Labels: Review effort 1/5

#451 pod spec labels
  armotypes/kubernetes_objects.go
Labels: Review effort 1/5

#452 Added cloud attributes
  identifiers/designators.go
Labels: Review effort 1/5

#455 Add HasTickets field to Vulnerability struct
  armotypes/vulnerabilitytypes.go
Labels: Review effort 1/5

#456 Add CreatedBy field to IntegrationReference struct
  notifications/integrationref.go
Labels: Review effort 1/5
